name = "grupo-uniao-lead-webhook"
main = "lead-webhook-worker.js"
compatibility_date = "2026-06-03"

[vars]
LEAD_WEBHOOK_URL = "https://webhook.simulead.com.br/webhook/e4ce4839-bb0c-4ade-ac79-7f5325be5104"
